FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less file
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool

COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/.libs
